import type { PortfolioContent } from "./types";

export const seedContent: PortfolioContent = {
  settings: {
    heroLine1: "Intentional",
    heroLine2: "Design.",
    name: "Bo Hubbard",
    credential: "B.S. Computer Science · Class of 2026",
    subtext:
      "Software development, graphic design, and interfaces built with purpose.",
    heroRoles: [
      "Software Developer",
      "App Developer",
      "UI Designer",
      "Graphic Designer",
    ],
    aboutHeading: "Bo Hubbard",
    aboutSubheading: "developer & designer",
    aboutParagraphs: [
      "I am a Computer Science graduate based in Chicago, IL. I like to combine technical development with my eye for design, aiming to create products and software that are intuitive and engaging.",
      "My passion for problem-solving drives everything I do. I'm motivated, competitive, and persistent. I like the challenge of turning complex ideas into real solutions, especially if they improve how people interact with technology. I am always looking for ways to make software more meaningful and effective.",
      "My roots in technology started early through playing video games and building on sandbox platforms like Roblox, where I discovered the crossroads of problem-solving and creativity. That foundation continues to shape my approach — curious, iterative, and focused.",
    ],
    aboutImageUrl: "/images/bo-hubbard-graduation.png",
    aboutImageAlt:
      "Bo Hubbard at ASU graduation in maroon and gold regalia",
    location: "Chicago, IL",
    timezone: "America/Chicago",
    metaTitle: "Bo Hubbard — Developer & Designer",
    metaDescription:
      "Portfolio of William (Bo) Hubbard — software developer, graphic designer, and ASU Computer Science graduate.",
    ogUrl: "https://bohubbard.xyz",
    resumeUrl: "/cv.pdf",
    resumeLabel: "Resume",
  },
  projects: [
    {
      id: "wkcc-perks",
      title: "WKCC Perks",
      subtitle: "iOS application",
      description:
        "Built from the ground up in Swift and SwiftUI — a perks directory connecting chamber members with 50 local partner businesses.",
      tags: ["Swift", "SwiftUI", "REST APIs", "iOS"],
      href: "https://github.com/bubb4rd/WKCC-Perks",
      category: "dev",
      accent: "#3B82F6",
      featured: true,
      image:
        "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1400&q=80&auto=format&fit=crop",
    },
    {
      id: "pantrypulse",
      title: "PantryPulse",
      subtitle: "Recipe tracking app",
      description:
        "Full-stack recipe app for discovering meals from available ingredients.",
      tags: ["React", "Tailwind CSS", "Firebase", "REST APIs"],
      href: "https://pantrypulse-22e13.firebaseapp.com/",
      category: "dev",
      accent: "#8B5CF6",
      image:
        "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=80&auto=format&fit=crop",
    },
    {
      id: "borgwithus",
      title: "Borgwithus",
      subtitle: "Cocktail generator",
      description: "A dynamic drink name generator with 300+ monthly users.",
      tags: ["React", "CSS", "HTML", "Netlify"],
      href: "https://borgwithus.xyz",
      category: "dev",
      accent: "#06B6D4",
      image:
        "https://images.unsplash.com/photo-1536935338788-846bb9981813?w=1200&q=80&auto=format&fit=crop",
    },
    {
      id: "bubbard",
      title: "BUBBARD Design",
      subtitle: "Freelance graphic design",
      description:
        "Digital graphics and visual content engaging 100+ users per post. Direct client collaboration to deliver designs aligned with brand vision across social platforms.",
      tags: ["Adobe Creative Suite", "Figma", "Social Media"],
      href: "https://be.net/bubbard/",
      category: "design",
      accent: "#F472B6",
      featured: true,
      image: "/images/bubbard-design-project.png",
    },
    {
      id: "banana",
      title: "Banana",
      subtitle: "Discord bot",
      description:
        "Multipurpose Discord bot built to increase interactivity in servers.",
      tags: ["Node.js", "MongoDB", "discord.js", "Heroku"],
      href: "https://discord.com/oauth2/authorize?client_id=1184364896071196672&permissions=8&scope=bot",
      category: "dev",
      accent: "#F59E0B",
      image: "/images/banana-project.jpg",
    },
    {
      id: "temporal-haven",
      title: "Temporal Haven",
      subtitle: "Command-line adventure",
      description:
        "Text adventure game — uncover corrupt governments and time travel through the terminal.",
      tags: ["C++", "CMake"],
      href: "https://github.com/bubb4rd/temporal_haven",
      category: "dev",
      accent: "#10B981",
      image: "/images/temporal.jpg",
    },
  ],
  timelineEntries: [
    {
      id: "wkcc",
      type: "work",
      title: "Software Development Intern",
      organization: "Wilmette Kenilworth Chamber of Commerce",
      location: "Wilmette, IL",
      start: "June 2026",
      end: "Present",
      description:
        "Building WKCC Perks, a SwiftUI app for 50+ local chamber businesses, and more.",
      accent: "#3B82F6",
      image: "/images/WKCCLogo.png",
      imageAlt: "iPhone displaying a mobile application interface",
    },
    {
      id: "asu-design",
      type: "work",
      title: "Graphic Design Assistant",
      organization: "Arizona State University",
      location: "Tempe, AZ",
      start: "Nov 2025",
      end: "May 2026",
      description: "On-brand graphics for university marketing and events.",
      accent: "#F472B6",
      image: "/images/A41.jpg",
      imageAlt:
        "Graphic design work created for Arizona State University marketing",
    },
    {
      id: "main-event",
      type: "work",
      title: "Technician",
      organization: "Main Event Entertainment",
      location: "Tempe, AZ",
      start: "Oct 2024",
      end: "May 2025",
      description: "Kept 100+ arcade and computer systems up and running.",
      accent: "#06B6D4",
      image:
        "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&q=80&auto=format&fit=crop",
      imageAlt: "Arcade entertainment floor with glowing game cabinets",
    },
    {
      id: "asu",
      type: "education",
      title: "B.S. Computer Science",
      organization: "Arizona State University",
      location: "Tempe, AZ",
      start: "Aug 2022",
      end: "May 2026",
      description:
        "Software Engineering, Human Computer Interaction, and design foundations.",
      accent: "#8B5CF6",
      image: "/images/asu.jpg",
      imageAlt: "Bo Hubbard at ASU graduation in maroon and gold regalia",
    },
  ],
  skillCategories: [
    {
      id: "languages",
      title: "Programming Languages",
      accent: "#3B82F6",
      skills: [
        { name: "JavaScript", icon: "javascript", accent: "#F7DF1E" },
        { name: "TypeScript", icon: "typescript", accent: "#3178C6" },
        { name: "Java", icon: "java", accent: "#007396" },
        { name: "C++", icon: "cplusplus", accent: "#00599C" },
        { name: "Python", icon: "python", accent: "#3776AB" },
        { name: "SQL", icon: "sql", accent: "#4479A1" },
        { name: "Swift", icon: "swift", accent: "#F05138" },
      ],
    },
    {
      id: "mobile",
      title: "Mobile Development",
      accent: "#F05138",
      skills: [
        { name: "iOS", icon: "ios", accent: "#000000" },
        { name: "Android", icon: "android", accent: "#3DDC84" },
      ],
    },
    {
      id: "web",
      title: "Web Development",
      accent: "#8B5CF6",
      skills: [
        { name: "React", icon: "react", accent: "#61DAFB" },
        { name: "Node.js", icon: "nodejs", accent: "#339933" },
        { name: "HTML", icon: "html", accent: "#E34F26" },
        { name: "CSS", icon: "css", accent: "#1572B6" },
        { name: "Tailwind CSS", icon: "tailwindcss", accent: "#06B6D4" },
        { name: "Three.js", icon: "threedotjs", accent: "#000000" },
        { name: "GSAP", icon: "gsap", accent: "#88CE02" },
        { name: "WordPress", icon: "wordpress", accent: "#21759B" },
        { name: "REST APIs", icon: "rest", accent: "#10B981" },
      ],
    },
    {
      id: "tools",
      title: "Tools & Technologies",
      accent: "#F472B6",
      skills: [
        { name: "Git", icon: "git", accent: "#F05032" },
        { name: "GitHub", icon: "github", accent: "#181717" },
        { name: "MongoDB", icon: "mongodb", accent: "#47A248" },
        { name: "Firebase", icon: "firebase", accent: "#DD2C00" },
        { name: "Figma", icon: "figma", accent: "#F24E1E" },
        { name: "Adobe Creative Suite", icon: "adobe", accent: "#FF0000" },
        { name: "Windows", icon: "windows", accent: "#0078D4" },
        { name: "Mac", icon: "mac", accent: "#555555" },
      ],
    },
  ],
  socialLinks: [
    { label: "GitHub", href: "https://github.com/bubb4rd", icon: "github" },
    {
      label: "LinkedIn",
      href: "https://www.linkedin.com/in/bo-hubbard-4988b2246/",
      icon: "linkedin",
    },
    { label: "Email", href: "mailto:bohubbard8@gmail.com", icon: "email" },
  ],
  resumeLink: {
    label: "Resume",
    href: "/cv.pdf",
  },
};
